### ISSUE TITLE
Max Rain Rate Does Not Reset

### ISSUE THREAD

**Issue by gary-hammer** [Daveiano/weewx-wdc#224] opened 2023-11-10 14:03 UTC
The max rain rate does not reset. The min may not but as it normally zero hard to tell.
That wasn't noticeable until now.
I have verified that all other min/max seem to be resetting.

_Originally posted by @gary-hammer in https://github.com/Daveiano/weewx-wdc/issues/198#issuecomment-1805782036_

**Comment by Daveiano** [comment] 2023-11-11 00:19
Just had a quick look into the code and it should reset the rainRate. There is a chance of rain for the coming days, so I will have a deeper look soon. 

Just to verify: You are talking about this max value in the Rain tile, right?

![GH-224-1](https://github.com/Daveiano/weewx-wdc/assets/3184897/428977ea-4fcf-435a-a587-f15a15ca062c)

**Comment by gary-hammer** [comment] 2023-11-11 01:11
Indeed, the highlighted value does not reset.

**Comment by gary-hammer** [comment] 2023-11-12 02:14
I changed the data feed to the MQTT from my weewx instance that uses a console logger.
It has a complete set of data and is updated every 2.5 seconds.

I'm attaching its output if you need to see it for some reason.
[Davis Logger MQTT Output.txt](https://github.com/Daveiano/weewx-wdc/files/13326968/Davis.Logger.MQTT.Output.txt)

**Comment by Daveiano** [comment] 2023-11-14 23:38
Ok, I think I found the bug. Attached is an updated live-updates.js file, please feel free to test this one out (it should alert "rainRate" on first load).

Take your time! I got the luck to have rain for the last 3 days to test this out in real-world conditions. 

[live-updates.zip](https://github.com/Daveiano/weewx-wdc/files/13358285/live-updates.zip)

**Comment by gary-hammer** [comment] 2023-11-15 02:39
Thanks, we're not expecting rain until the weekend.

I do notice an odd behavior.
The apptemp and dewpoint change between two values every loop.
These are different pairs of values. Like 30.5 and 29.4 for apptemp. I have not seen this before.
Perhaps dew point should only change with the archive?
Anyway, I shall report back once it rains.

**Comment by gary-hammer** [comment] 2023-11-15 14:39
To make the two value issue more clear, I have a short video of this.
Notice the apptemp alternates between what looks like the real apptemp and in this case 34 F
The dew point does the same but it isn't as clear.

https://ghammer.net/tab.mp4

Let me know after you view it so I can remove the file.

**Comment by Daveiano** [comment] 2023-11-15 16:55
I downloaded the video, thank you.

I will have a look at it as soon as possible, reporting back!

**Comment by Daveiano** [comment] 2023-11-16 00:19
> To make the two value issue more clear, I have a short video of this.
Notice the apptemp alternates between what looks like the real apptemp and in this case 34 F
The dew point does the same but it isn't as clear.

I see what is happening, but I can not reproduce it. Realy can't make any sense out of it. 

Do you probably have a second MQTT-enabled skin installed to prove if it's the skin's fault or another problem?

**Comment by gary-hammer** [comment] 2023-11-16 01:24
I shall install belchertown in the morning.

It is installed on the live machine and uses the same MQTT feed as this.

But to remove any difference, I'll install on the same machine.

**Comment by gary-hammer** [comment] 2023-11-16 15:26
My main server has a rather odd configuration.
Weather is served from /home/weather/bt
I have installed WDC there and I'm having a time with getting the html_root and base_path set correctly.
This is among the entries I've tried. Where oh where have I went wrong?
[[WdcReport]]
        HTML_ROOT = /home/weather/bt/wdc
        base_path = /wdc/

**Comment by Daveiano** [comment] 2023-11-16 16:22
The `base_path` only depends on  your web server configuration and how you  are accessing the skin. 

So if you are accessing the webpage:
- via http://host.com/, the `base_path` should be `base_path = /`
- via http://host.com/abc, the `base_path` should be `base_path = /abc`
- via http://host.com/abc/def, the `base_path` should be `base_path = /abc/def`

See https://github.com/Daveiano/weewx-wdc/wiki/WeeWX-related#setting-html_root-and-basepath

**Comment by gary-hammer** [comment] 2023-11-16 17:59
https://weather.ghammer.net/wdc/
There is nothing I have tried that works. I just get the framework with no content.
Perhaps this needs to be in Extras?

[[WdcReport]]
        HTML_ROOT = /home/weather/bt/wdc
        base_path = /wdc

**Comment by Daveiano** [comment] 2023-11-17 00:05
Sorry, it needs the ending slash:

`base_path = /wdc/`

**Comment by gary-hammer** [comment] 2023-11-17 01:43
Bingo!
https://weather.ghammer.net/wdc/

No issue on my production server. This is the release version. I'll add the 'rain' version in the morning.

**Comment by gary-hammer** [comment] 2023-11-17 15:14
Well, I think I will wipe and reinstall the test server. I'll let it go through the rain that is forecast to be certain the rate is reset first.

Taking lots of errors now. This is with the 'rain' file installed there. It is not on the production server and all is well there, no errors.
I'm attaching the errors here for you, just in case.
[wdc_errors.txt](https://github.com/Daveiano/weewx-wdc/files/13393482/wdc_errors.txt)

**Comment by Daveiano** [comment] 2023-11-17 17:48
> No issue on my production server. This is the release version. I'll add the 'rain' version in the morning.

> Taking lots of errors now. This is with the 'rain' file installed there. It is not on the production server and all is well there, no errors.

So this sounds like the "alternating two value issue" is solved, right?

> I'm attaching the errors here for you, just in case.

I have never seen such errors while developing. This is with weewx 4.10.2, right?

**Comment by gary-hammer** [comment] 2023-11-17 18:37
On the test server/instance, the alternating values continue. It encompasses apptemp, heat index, wind chill, and dew point.
That machine is the only one with the test 'rain_rate' file installed. It is also the one with the errors. It runs weewx v5

I installed, with your help, on my production machine. It runs weewx 4.10.2. No errors in the logs and no alternating values.

I plan to keep the test instance until rain comes to test the fix for the reset. Afterwards, I'm going to install Debian and weewx fresh and install the current release of WDC skin.

**Comment by Daveiano** [comment] 2023-11-18 00:00
> On the test server/instance, the alternating values continue. It encompasses apptemp, heat index, wind chill, and dew point.
That machine is the only one with the test 'rain_rate' file installed. It is also the one with the errors. It runs weewx v5

Ok so the updated "rain file" should not produce these errors, it's not involved when the files are generated by Cheetah, so I assume this is WeeWX v5 related. I did not test the skin with v5 yet. How is the current progress, are we near a stable v5 release, yet?

> I installed, with your help, on my production machine. It runs weewx 4.10.2. No errors in the logs and no alternating values.
> I plan to keep the test instance until rain comes to test the fix for the reset. Afterwards, I'm going to install Debian and weewx fresh and install the current release of WDC skin.

Sounds great!

**Comment by gary-hammer** [comment] 2023-11-18 00:09
V5 is stable, there are packaging issues as I understand.
This could be a python issue, there have been reports on the WeeWX group of various issues with an updated python.
Not worth the time to troubleshoot as different drivers and skins have been in and out of the test machine and a clean install is in order. Since it is proxmox, I'll just save the image and be able to restore in about a minute going forward.

Rain forecast for my overnight, so Sunday morning I'll know if the reset functions.

**Comment by gary-hammer** [comment] 2023-11-18 17:36
Well, I see that we have had rain since midnight.
The instance on my production server (strictly stock install) shows a max rain rate for the day.
The instance on my test server shows the rain amount but 0 for max rain rate when I open it on a PC. On the tablet where it is always open, it is showing the correct max rain rate for the day.
I'd think it should show the max values no matter when it were opened.

**Comment by gary-hammer** [comment] 2023-11-19 11:31
Max rain rate did reset with the 'rain' skin.

**Comment by gary-hammer** [comment] 2023-11-19 12:09
The alternating values was apparently caused by the MQTTSubscribe driver. I returned to the WLL driver and the issue is gone.

**Comment by Daveiano** [comment] 2023-11-20 00:45
> Max rain rate did reset with the 'rain' skin.

Great, then this change will come to the next release.

> The instance on my production server (strictly stock install) shows a max rain rate for the day.
The instance on my test server shows the rain amount but 0 for max rain rate when I open it on a PC. On the tablet where it is always open, it is showing the correct max rain rate for the day.
I'd think it should show the max values no matter when it were opened.

I think I know what's causing this, looks like a bug. I will give you an updated file for testing within this week, if you do not find any other bugs, this version will be in the next release.

Thank you for all the testing!

**Comment by gary-hammer** [comment] 2023-11-20 01:23
Sounds good. Thanks for your rapid fixes!

**Comment by Daveiano** [comment] 2023-11-21 22:23
Here is an updated file (this time without an alert) which should fix the problem described in https://github.com/Daveiano/weewx-wdc/issues/224#issuecomment-1817578790 AND the rain rate issue.

So please feel free to test this out extensively and report back any problems!

[live-updates.zip](https://github.com/Daveiano/weewx-wdc/files/13431528/live-updates.zip)

**Comment by gary-hammer** [comment] 2023-11-21 22:59
Thanks. File is loaded on both systems.
Just in time, we'll have rain and snow over the next two days.

I'll report back afterwards.

**Comment by gary-hammer** [comment] 2023-11-23 15:49
Rain yesterday, all was well.
This morning, max rain rate is cleared.

As it is our Thanksgiving holiday, I won't be around until Monday.

I'm happy with the results, so feel free to close this ticket.

**Comment by Daveiano** [comment] 2023-11-25 00:00
Great! Please feel free to open a new issue/discussion if you find another bug.

I wish you a happy Thanksgiving!

**Closed as completed by Daveiano** 2023-11-25 00:00 UTC
Labels: bug, MQTT
