### ISSUE TITLE
Html path problem

### ISSUE THREAD

**Issue by wifi75** [Daveiano/weewx-wdc#129] opened 2023-03-13 08:10 UTC
I reinstalled everything , a fresh install .
pho problems with displaying the skin, it seems that the skint points to /html path and does not have /html/weewx

```
in the weewx configuration it is set like this:
[StdReport]
    
    # Where the skins reside, relative to WEEWX_ROOT
    SKIN_ROOT = /etc/weewx/skins
    
    # Where the generated reports should go, relative to WEEWX_ROOT
    HTML_ROOT = /var/www/html/weewx/
```

below where it generated the skin.
![image](https://user-images.githubusercontent.com/31816231/224641794-93d76ba4-c3d7-46f0-a913-b9201658fb4f.png)

here is the result of the html page
![image](https://user-images.githubusercontent.com/31816231/224643020-04e6b2e3-7127-4bd6-b6e6-d10ab2240edf.png)

why?

**Comment by wifi75** [comment] 2023-03-13 09:08
solved my self by editing skin.conf 
**base_path = /weewx/**

```
# configuration file for the weewx-wdc skin
SKIN_NAME = Weather Data Center
SKIN_VERSION = 3.0.1

[ObservationBindings]
    [[custom_obs_1]]
        data_binding = extension_1_binding # eg wx_binding
        observation = obs_key # eg. outTemp
    [[custom_obs_2]]
        data_binding = extension_2_binding
        observation = another_obs_key

[Extras]
    # If weewx is installed in some sub-folder of your web server,
    # please specify the path here.
    **base_path = /weewx/**
```

**Comment by Daveiano** [comment] 2023-03-13 10:19
Ok so it's now working for you? :)

Duplicate of #126

**Comment by wifi75** [comment] 2023-03-13 10:36
yes

**Closed as completed** 2023-03-13 10:49 UTC
Labels: support
