### ISSUE TITLE
[BUG] Some built-in fields require adding an entry to [[Icons]]

### ISSUE THREAD

**Issue by nifoc** [Daveiano/weewx-wdc#124] opened 2023-03-07 16:52 UTC
**Describe the bug**
WeeWX: 4.10.2
weewx-wdc: 3.0.0

Adding certain entries to `stat_tile_observations` raises a `TypeError`, which is ultimately caused by a missing entry under `[[Icons]]`.

```
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: Evaluation of template /home/weewx/skins/weewx-wdc/week.html.tmpl failed with exception '<class 'TypeError'>'
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/weewx-wdc/week.html.tmpl
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: **** Reason: argument of type 'NoneType' is not iterable
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 348, in generate
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_week_html_tmpl.py", line 193, in respond
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "/opt/venv/lib/python3.10/site-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_body_alternative_inc.py", line 215, in respond
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "/opt/venv/lib/python3.10/site-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_weewx_wdc_includes_stat_tile_inc.py", line 346, in respond
Mar  7 17:18:22 weewx[66] ERROR weewx.cheetahgenerator: ****  TypeError: argument of type 'NoneType' is not iterable
```

This happens for all templates (not just `week.html.tmpl`). At least the following entries cause the above exception:

* `pm1_0`
* `pm2_5`
* `pm10_0`

Adding something like this as a workaround helps (but will obviously result in a "wrong" icon):

```
    [[Icons]]
        pm1_0 = "includes/icons/signal.svg"
        pm2_5 = "includes/icons/signal.svg"
        pm10_0 = "includes/icons/signal.svg"
        #rain = "includes/icons/barometer.svg"
```

**To Reproduce**
1. Add an entry for `pm1_0` to `stat_tile_observations`
2. Wait for the report to be re-generated
3. See the above error

**Expected behavior**
Especially all "native" WeeWX types should not require adding an entry to `[[Icons]]`. There should be a kind of "fallback icon" if no icon has been configured.

**Comment by Daveiano** [comment] 2023-03-08 00:10
Bug fixed in [39b7101](https://github.com/Daveiano/weewx-wdc/commit/39b7101e06ec3b81b22e5757584074e7720a1c7c).

I decided not to add a "default icon", I don't know... I think it would look pretty weird to have the same icon for (probably) multiple different observations!? This way no icons are shown when displaying an unrecognized observation.

Btw: I could not find any appropriate icons for the `group_concentration` observations (no2, pm1_0, pm2_5, pm10_0), but what about this:

![face--mask](https://user-images.githubusercontent.com/3184897/223584132-b954bef9-e46f-4b9c-aa11-085fa71ea9ac.svg)

Some `group_fraction` observations (co, co2, o3, so2) could probably also use this icon, what do you think?
If you have a suggestion for a better-suited icon, I am open to this. Btw, I am mainly using these icons here: https://carbondesignsystem.com/guidelines/icons/library/

**Note:** I will wait till the end of the week if more bugs hit with v3.0.0, then there will be a new bugfix release, but you can test the changes from the commit if you like.

And thank you very much for the detailed bug reports, a pleasure to work with.

**Comment by nifoc** [comment] 2023-03-08 10:07
> This way no icons are shown when displaying an unrecognized observation.

This is even better than having a default icon!

> [mask icon]

I looked through the list of icons and I agree that the mask one is probably the best for these "air pollutant" observations.

> Some group_fraction observations (co, co2, o3, so2) could probably also use this icon, what do you think?

I couldn't find an icon that might work for these, apart from maybe the mask icon again. But that would mean the mask is used for 7+ observations, which feels like it would be a bit too much? (Assuming someone can collect/display all these observations)

Maybe simply not having an icon for these is still the best solution? iirc that's basically what the previous version did.

> And thank you very much for the detailed bug reports, a pleasure to work with.

Thank you for creating weewx-wdc 🙂 

I might have to learn at least a bit of Python to provide these fixes myself in the future 😅

**Comment by Daveiano** [comment] 2023-03-09 01:00
>>This way no icons are shown when displaying an unrecognized observation.

>This is even better than having a default icon!

This is the intended behaviour (not showing icons for unrecognized observations). This bug must be a regression of #87 

I added the mask icon for no2, pm1_0, pm2_5 and pm10_0.

> I couldn't find an icon that might work for these, apart from maybe the mask icon again. But that would mean the mask is used for 7+ observations, which feels like it would be a bit too much? (Assuming someone can collect/display all these observations)

You are right, using the icon for too much observations wont be a good idea, I will be on the lookout for any new icons here.

> I might have to learn at least a bit of Python to provide these fixes myself in the future sweat_smile

PR's are highly appreciated :)

**Closed as completed by Daveiano** 2023-03-09 00:59 UTC
Labels: bug
